stages:
  - test
  - build

testing:
  image: node:latest
  cache:
    paths:
      - node_modules/
  stage: test
  script:
    - npm install
    - npm run test-ci
    - npm run coverage
  only:
    - develop
    - master
  tags:
    - docker

building:
  image: docker:latest
  stage: build
  only:
    - develop
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  tags:
    - docker
