version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - db_mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev-net
    restart: always

volumes:
  db_mongo:

networks:
  dev-net:
    external:
      name: "development"
