version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - db_mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev-net
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - db_redis:/data
    restart: always

  api:
    build: .
    container_name: api
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/koa
    networks:
      - dev-net
    logging:
      options:
        max-size: 10m
        max-file: "10"
    restart: always

volumes:
  db_mongo:
  db_redis:

networks:
  dev-net:
    external:
      name: "development"
